import type { Metadata } from "next";
import "./globals.css";
import { Albert_Sans } from "next/font/google";
import PrelineScript from "@/components/preline/Preline";



const sans = Albert_Sans({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sans.className}>{children}</body>
      <PrelineScript />
    </html>
  );
}
